language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  provider: npm
  email: 'devmonk@mediamonks.com'
  api_key:
    secure: ''
  on:
    tags: true
    node: '4'
  skip_cleanup: true

addons:
  code_climate:
    repo_token:
       secure: "guWxP0nW7S/QZBvhdu7jCsOmnNv2EZlXJVlzb5Oz9E6cjw7LngOApNUZv+W8+nCf+HVaFC4gIzhrvd7hjIcir7RrvthRHIpNyhKRrBPLIHPjT5gMgr4QPI0THTOyjU4aBO3sZhTMqWQQY1b5Kupp+PW6ZMYDphC2pGTLWeVV/MbFh/qcC6lS/eh9G0OqzYfftYOoYdXBls79AnbSf54B0gxUnwO1yaDi0ZyFi+I6fMkZhP7BHaaUdp6gVrZyGva4UEs34x/PIQBrayXVe699o1o4a/aWS4uCxjzUoToGRQQFgrDt1lcZhhZZheRg7/uJ/xNZWTdlaXxhwU4gPr7eUWJ9qB8ubkUrIWKYSvNNfwJJLgD2uig/Ak2wTjMj/lwgI++x1+0v696YaWatqI3sVcM667i+syajAcSkINRJhi1cZ2dWJsC2FmL83ih6iVrE7413h2f8gr9rxIKHoYSsCQBtdjgpZSu61EOHgPApE677YLUiivGW+60yv0fGhTDdeMqUv9oYRfglOPepaYIbFLShHP2xgXKzK/JQiTdD9b4DNo1JbffaYPkvwki+7718eqbUJ0jQs6ONb8vyAzxAvft7mzF5WBKMCQdHQE0WMFocdzuvM19opseJ8GMJdQeWp+3AEbeibz9YKK5RSEpYaAB2H8B1sKPwusA9oq7VNfE="
